//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObservatorioBack.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processo()
        {
            this.Acompanhamentos = new HashSet<Acompanhamento>();
        }
    
        public int Id { get; set; }
        public string Numero { get; set; }
        public System.DateTime DataInicio { get; set; }
    
        public virtual Detento Detento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acompanhamento> Acompanhamentos { get; set; }
    }
}
